// <auto-generated />
using System;
using CRMService.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMService.DataBase.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251019130023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMService.Models.Authorization.BlockReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("BlockingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("blocking_date");

                    b.Property<string>("ReasonBlock")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("reason_block");

                    b.Property<DateTime?>("UnblockingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("unblocking_date");

                    b.Property<string>("UnblockingReason")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("reason_unblock");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("block_reason", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.Authorization.CrmRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("crm_role", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.Authorization.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ExpirationRefreshToken")
                        .HasColumnType("datetime")
                        .HasColumnName("expiration_refresh_token");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "user_session_id_idx");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.Authorization.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Login" }, "login_UNIQUE")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Company", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("AdditionalName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("additional_name");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId_idx");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.CompanyCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("company_category", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("login");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EmployeeGroup", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.HasKey("EmployeeId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("employee_groups", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("employee_roles", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("inventory_number");

                    b.Property<int?>("KindId")
                        .HasColumnType("int")
                        .HasColumnName("kindId");

                    b.Property<int?>("MaintenanceEntitiesId")
                        .HasColumnType("int")
                        .HasColumnName("maintenanceEntitiesId");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturerId");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("modelId");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "companyId_idx");

                    b.HasIndex(new[] { "KindId" }, "kindId_idx");

                    b.HasIndex(new[] { "MaintenanceEntitiesId" }, "maintenanceEntitiesId_idx");

                    b.HasIndex(new[] { "ManufacturerId" }, "manufacturerEquipId_idx");

                    b.HasIndex(new[] { "ModelId" }, "modelEquipId_idx");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EquipmentParameter", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipmentId");

                    b.Property<int>("KindParameterId")
                        .HasColumnType("int")
                        .HasColumnName("kindParameterId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("value");

                    b.HasKey("EquipmentId", "KindParameterId");

                    b.HasIndex(new[] { "EquipmentId" }, "equipmentId_idx");

                    b.HasIndex(new[] { "KindParameterId" }, "kindParameterId_idx");

                    b.ToTable("equipment_parameter", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Group", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Issue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int")
                        .HasColumnName("assignee_id");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline_at");

                    b.Property<DateTime?>("DelayTo")
                        .HasColumnType("datetime")
                        .HasColumnName("delay_to");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EmployeesUpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("employees_updated_at");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int")
                        .HasColumnName("priorityId");

                    b.Property<int?>("ServiceObjectId")
                        .HasColumnType("int")
                        .HasColumnName("service_objectId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("typeId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AssigneeId" }, "issue_assigneeId_idx");

                    b.HasIndex(new[] { "CompanyId" }, "issue_companyId_idx");

                    b.HasIndex(new[] { "PriorityId" }, "issue_priorityId_idx");

                    b.HasIndex(new[] { "ServiceObjectId" }, "issue_service_objectId_idx");

                    b.HasIndex(new[] { "StatusId" }, "issue_statusId_idx");

                    b.HasIndex(new[] { "TypeId" }, "issue_typeId_idx");

                    b.ToTable("issue", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssuePriority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.Property<int?>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("issue_priority", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("issue_status", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AvailableForClient")
                        .HasColumnType("bit")
                        .HasColumnName("available_for_client");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("code");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsInner")
                        .HasColumnType("bit")
                        .HasColumnName("is_inner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "groupId_idx");

                    b.ToTable("issue_type", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int")
                        .HasColumnName("parent_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("issue_type_groups", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Kind", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("kind", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.KindParam", b =>
                {
                    b.Property<int>("KindId")
                        .HasColumnType("int")
                        .HasColumnName("kindId");

                    b.Property<int>("KindParameterId")
                        .HasColumnType("int")
                        .HasColumnName("kindParameterId");

                    b.HasKey("KindId", "KindParameterId");

                    b.HasIndex(new[] { "KindId" }, "kindKey_idx");

                    b.HasIndex(new[] { "KindParameterId" }, "kindParameters_idx");

                    b.ToTable("kindparams", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.KindsParameter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("FieldType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("fieldType");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("kinds_parameters", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "companyId_idx");

                    b.ToTable("maintenance_entity", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Model", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<int>("KindId")
                        .HasColumnType("int")
                        .HasColumnName("kindId");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KindId" }, "kindId_idx");

                    b.HasIndex(new[] { "ManufacturerId" }, "manufacturerId_idx");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.OkdeskRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("okdesk_role", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<int>("IssueId")
                        .HasColumnType("int")
                        .HasColumnName("issueId");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<double>("SpentTime")
                        .HasColumnType("float")
                        .HasColumnName("spentTime");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmployeeId" }, "employeeId_idx");

                    b.HasIndex(new[] { "IssueId" }, "issueId_idx");

                    b.ToTable("time_entry", (string)null);
                });

            modelBuilder.Entity("CRMService.Models.Authorization.BlockReason", b =>
                {
                    b.HasOne("CRMService.Models.Authorization.User", "User")
                        .WithOne("BlockReason")
                        .HasForeignKey("CRMService.Models.Authorization.BlockReason", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_block_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Models.Authorization.Session", b =>
                {
                    b.HasOne("CRMService.Models.Authorization.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_session_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Models.Authorization.UserRole", b =>
                {
                    b.HasOne("CRMService.Models.Authorization.CrmRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_id");

                    b.HasOne("CRMService.Models.Authorization.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Company", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.CompanyCategory", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EmployeeGroup", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Models.OkdeskEntity.Group", "Group")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EmployeeRole", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Models.OkdeskEntity.OkdeskRole", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Equipment", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Company", "Company")
                        .WithMany("Equipment")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipmentCompanyId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("Equipment")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("kindEquipId");

                    b.HasOne("CRMService.Models.OkdeskEntity.MaintenanceEntity", "MaintenanceEntities")
                        .WithMany("Equipment")
                        .HasForeignKey("MaintenanceEntitiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("equipmentMaintenanceEntitiesId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("manufacturerEquipId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Model", "Model")
                        .WithMany("Equipment")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Kind");

                    b.Navigation("MaintenanceEntities");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.EquipmentParameter", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Equipment", "Equipment")
                        .WithMany("Parameters")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Models.OkdeskEntity.KindsParameter", "KindParameter")
                        .WithMany("Parameters")
                        .HasForeignKey("KindParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("KindParameter");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Issue", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Employee", "Assignee")
                        .WithMany("Issues")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("issue_assigneeId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Company", "Company")
                        .WithMany("Issues")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("issue_companyId");

                    b.HasOne("CRMService.Models.OkdeskEntity.IssuePriority", "Priority")
                        .WithMany("Issues")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("issue_priorityId");

                    b.HasOne("CRMService.Models.OkdeskEntity.MaintenanceEntity", "ServiceObject")
                        .WithMany("Issues")
                        .HasForeignKey("ServiceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("issue_service_objectId");

                    b.HasOne("CRMService.Models.OkdeskEntity.IssueStatus", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("issue_statusId");

                    b.HasOne("CRMService.Models.OkdeskEntity.IssueType", "Type")
                        .WithMany("Issues")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("issue_typeId");

                    b.Navigation("Assignee");

                    b.Navigation("Company");

                    b.Navigation("Priority");

                    b.Navigation("ServiceObject");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueType", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.IssueTypeGroup", "Group")
                        .WithMany("Types")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.IssueTypeGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.KindParam", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("KindParams")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("kindPrm");

                    b.HasOne("CRMService.Models.OkdeskEntity.KindsParameter", "KindParameter")
                        .WithMany("KindParams")
                        .HasForeignKey("KindParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("kindParameters");

                    b.Navigation("Kind");

                    b.Navigation("KindParameter");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Company", "Company")
                        .WithMany("MaintenanceEntities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("companyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Model", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("Models")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("kindId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("manufacturerId");

                    b.Navigation("Kind");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.TimeEntry", b =>
                {
                    b.HasOne("CRMService.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("employeeId");

                    b.HasOne("CRMService.Models.OkdeskEntity.Issue", "Issue")
                        .WithMany("TimeEntries")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("issueId");

                    b.Navigation("Employee");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("CRMService.Models.Authorization.CrmRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CRMService.Models.Authorization.User", b =>
                {
                    b.Navigation("BlockReason");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Company", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Issues");

                    b.Navigation("MaintenanceEntities");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.CompanyCategory", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Employee", b =>
                {
                    b.Navigation("EmployeeGroups");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("Issues");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Equipment", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Group", b =>
                {
                    b.Navigation("EmployeeGroups");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Issue", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssuePriority", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueStatus", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueType", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Kind", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("KindParams");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.KindsParameter", b =>
                {
                    b.Navigation("KindParams");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Manufacturer", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.Model", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CRMService.Models.OkdeskEntity.OkdeskRole", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
