// <auto-generated />
using System;
using CRMService.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMService.Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.BlockReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("BlockingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonBlock")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UnblockingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnblockingReason")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BlockReason", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.CrmRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("CrmRole", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("ExpirationRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "user_session_id_idx");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Login" }, "login_UNIQUE")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.GeneralSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("PlanSwitchSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PlanColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.PlanColorScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FromPercent")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ToPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "FromPercent", "ToPercent");

                    b.ToTable("PlanColorSchemes");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.PlanSetting", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanValue")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PlanSetting");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Company", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasJsonPropertyName("additional_name");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId_idx");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.CompanyCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CompanyCategory", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("LastName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Phone")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Position")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EmployeeGroup", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("EmployeeGroups", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("KindId")
                        .HasColumnType("int");

                    b.Property<int?>("MaintenanceEntitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "companyId_idx");

                    b.HasIndex(new[] { "KindId" }, "kindId_idx");

                    b.HasIndex(new[] { "MaintenanceEntitiesId" }, "maintenanceEntitiesId_idx");

                    b.HasIndex(new[] { "ManufacturerId" }, "manufacturerEquipId_idx");

                    b.HasIndex(new[] { "ModelId" }, "modelEquipId_idx");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EquipmentParameter", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("KindParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId", "KindParameterId");

                    b.HasIndex(new[] { "EquipmentId" }, "equipmentId_idx");

                    b.HasIndex(new[] { "KindParameterId" }, "kindParameterId_idx");

                    b.ToTable("EquipmentParameter", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Group", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Issue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DelayTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmployeesUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceObjectId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AssigneeId" }, "issue_assigneeId_idx");

                    b.HasIndex(new[] { "CompanyId" }, "issue_companyId_idx");

                    b.HasIndex(new[] { "PriorityId" }, "issue_priorityId_idx");

                    b.HasIndex(new[] { "ServiceObjectId" }, "issue_service_objectId_idx");

                    b.HasIndex(new[] { "StatusId" }, "issue_statusId_idx");

                    b.HasIndex(new[] { "TypeId" }, "issue_typeId_idx");

                    b.ToTable("Issue", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssuePriority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Color")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IssuePriority", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Color")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("IssueStatus", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("AvailableForClient")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInner")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "groupId_idx");

                    b.ToTable("IssueType", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("IssueTypeGroups", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Kind", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kind", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.KindParam", b =>
                {
                    b.Property<int>("KindId")
                        .HasColumnType("int");

                    b.Property<int>("KindParameterId")
                        .HasColumnType("int");

                    b.HasKey("KindId", "KindParameterId");

                    b.HasIndex(new[] { "KindId" }, "kindKey_idx");

                    b.HasIndex(new[] { "KindParameterId" }, "kindParameters_idx");

                    b.ToTable("KindParams", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.KindsParameter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FieldType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("KindsParameters", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "companyId_idx");

                    b.ToTable("MaintenanceEntity", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Model", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KindId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KindId" }, "kindId_idx");

                    b.HasIndex(new[] { "ManufacturerId" }, "manufacturerId_idx");

                    b.ToTable("Model", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.OkdeskRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OkdeskRole", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("SpentTime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmployeeId" }, "employeeId_idx");

                    b.HasIndex(new[] { "IssueId" }, "issueId_idx");

                    b.ToTable("TimeEntry", (string)null);
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.BlockReason", b =>
                {
                    b.HasOne("CRMService.Domain.Models.Authorization.User", "User")
                        .WithOne("BlockReason")
                        .HasForeignKey("CRMService.Domain.Models.Authorization.BlockReason", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.Session", b =>
                {
                    b.HasOne("CRMService.Domain.Models.Authorization.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.UserRole", b =>
                {
                    b.HasOne("CRMService.Domain.Models.Authorization.CrmRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.Authorization.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.PlanColorScheme", b =>
                {
                    b.HasOne("CRMService.Domain.Models.CrmEntities.Plan", "Plan")
                        .WithMany("PlanColorSchemes")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.PlanSetting", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("PlanSettings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.CrmEntities.Plan", "Plan")
                        .WithMany("PlanSettings")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Company", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.CompanyCategory", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EmployeeGroup", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Group", "Group")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EmployeeRole", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.OkdeskRole", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Equipment", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Company", "Company")
                        .WithMany("Equipment")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("Equipment")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.MaintenanceEntity", "MaintenanceEntities")
                        .WithMany("Equipment")
                        .HasForeignKey("MaintenanceEntitiesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Manufacturer", "Manufacturer")
                        .WithMany("Equipment")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Model", "Model")
                        .WithMany("Equipment")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Kind");

                    b.Navigation("MaintenanceEntities");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.EquipmentParameter", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Equipment", "Equipment")
                        .WithMany("Parameters")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.KindsParameter", "KindParameter")
                        .WithMany("Parameters")
                        .HasForeignKey("KindParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("KindParameter");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Issue", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Employee", "Assignee")
                        .WithMany("Issues")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Company", "Company")
                        .WithMany("Issues")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.IssuePriority", "Priority")
                        .WithMany("Issues")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.MaintenanceEntity", "ServiceObject")
                        .WithMany("Issues")
                        .HasForeignKey("ServiceObjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.IssueStatus", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.IssueType", "Type")
                        .WithMany("Issues")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");

                    b.Navigation("Company");

                    b.Navigation("Priority");

                    b.Navigation("ServiceObject");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueType", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.IssueTypeGroup", "Group")
                        .WithMany("Types")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.IssueTypeGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.KindParam", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("KindParams")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.KindsParameter", "KindParameter")
                        .WithMany("KindParams")
                        .HasForeignKey("KindParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");

                    b.Navigation("KindParameter");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Company", "Company")
                        .WithMany("MaintenanceEntities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Model", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Kind", "Kind")
                        .WithMany("Models")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kind");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.TimeEntry", b =>
                {
                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Employee", "Employee")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMService.Domain.Models.OkdeskEntity.Issue", "Issue")
                        .WithMany("TimeEntries")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.CrmRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CRMService.Domain.Models.Authorization.User", b =>
                {
                    b.Navigation("BlockReason");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CRMService.Domain.Models.CrmEntities.Plan", b =>
                {
                    b.Navigation("PlanColorSchemes");

                    b.Navigation("PlanSettings");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Company", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Issues");

                    b.Navigation("MaintenanceEntities");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.CompanyCategory", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Employee", b =>
                {
                    b.Navigation("EmployeeGroups");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("Issues");

                    b.Navigation("PlanSettings");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Equipment", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Group", b =>
                {
                    b.Navigation("EmployeeGroups");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Issue", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssuePriority", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueStatus", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueType", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.IssueTypeGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Kind", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("KindParams");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.KindsParameter", b =>
                {
                    b.Navigation("KindParams");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.MaintenanceEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Manufacturer", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.Model", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CRMService.Domain.Models.OkdeskEntity.OkdeskRole", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}



